name: dcli_scripts
version: 1.15.6-dev.3
description: A collection of cli scripts that do odd jobs for me.
repository: https://github.com/bsutton/dcli_scripts
environment: 
  sdk: '>=2.14.0 <3.0.0'
dependencies: 
  args: ^2.1.1
  dcli: ^1.14.1
  docker2: ^2.1.2
  path: ^1.6.4
  pub_release: ^7.1.16
  settings_yaml: ^3.0.6
  uuid: ^3.0.5
dev_dependencies: 
  lint_hard: ^1.0.0
  test: ^1.20.1
executables: 
  add_gnome_launcher: 
  artifactory: 
  certbot_renew: 
  clean: 
  dcompress: 
  dcopydir: 
  denv: 
  dfind: 
  dmailhog: 
  dnsflush: 
  docker_dcli: 
  docker_push: 
  downit: 
  dmysql: 
  dpath: 
  dport: 
  dreplace: 
  dsetver: 
  dsort: 
  dvirtualbox: 
  dwc: 
  dwhich: 
  dzfs_clean: 
  eclipse_launcher: 
  find_old_dart_packages: 
  find_text: 
  gitadd_team_to_repository: 
  gitcreation_date: 
  gitgc: 
  gituncommited: 
  gitsyncfork: 
  gitupdate_remote: 
  hexdump: 
  hog: 
  install_flutter: 
  ipaddr: 
  kill_tomcat: 
  pub_get_all: 
