name: dcli_scripts
version: 3.0.0
description: A collection of cli scripts that do odd jobs for me.
repository: https://github.com/bsutton/dcli_scripts
environment: 
  sdk: '>=2.19.0-444.2.beta <3.0.0'
dependencies: 
  args: ^2.3.1
  dcli: ^2.0.0-beta.1
  docker2: ^3.0.0
  path: ^1.8.2
  pub_release: ^9.0.0-beta.1
  settings_yaml: ^5.0.0
  uuid: ^3.0.6
  win32: ^4.1.4
dev_dependencies: 
  lint_hard: ^3.0.0-beta.1
  test: ^1.20.1
executables: 
  add_gnome_launcher: 
  artifactory: 
  bobthefish: 
  certbot_renew: 
  clean: 
  dcompress: 
  dcopydir: 
  denv: 
  dfind: 
  dmailhog: 
  dnsflush: 
  docker_dcli: 
  docker_push: 
  downit: 
  dmysql: 
  dpath: 
  dport: 
  dreplace: 
  dsetver: 
  dsort: 
  dvirtualbox: 
  dwc: 
  dwhich: 
  dzfs_clean: 
  eclipse_launcher: 
  find_old_dart_packages: 
  find_text: 
  gactivate: 
  gitadd_team_to_repository: 
  gitcreation_date: 
  gitgc: 
  gituncommited: 
  gitsyncfork: 
  gitupdate_remote: 
  hexdump: 
  hog: 
  install_flutter: 
  ipaddr: 
  kill_tomcat: 
  pub_get_all: 
