name: dcli_scripts
version: 1.0.7
description: A collection of cli scripts that do odd jobs for me.
repository: https://github.com/bsutton/dcli_scripts
environment: 
  sdk: '>=2.14.0 <3.0.0'
dependencies: 
  dcli: ^1.9.1
  args: ^2.1.1
  path: ^1.6.4
  settings_yaml: ^3.0.6
  docker2: ^2.0.1
dev_dependencies: 
  lints: ^1.0.0
dependency_overrides: 
  dcli: 
    path: ../dcli
executables: 
  add_gnome_launcher: 
  artifactory: 
  certbot_renew: 
  clean: 
  dcompress: 
  dcopydir: 
  denv: 
  dfind: 
  dmailhog: 
  dmysql: 
  dnsflush: 
  docker_dcli: 
  downit: 
  dpath: 
  dport: 
  dreplace: 
  dsort: 
  dvirtualbox: 
  dwc: 
  dwhich: 
  dzfs_clean: 
  eclipse_launcher: 
  find_old_dart_packages: 
  gitadd_team_to_repository: 
  gitcreation_date: 
  gitgc: 
  gituncommited: 
  gitsyncfork: 
  gitupdate_remote: 
  hexdump: 
  hog: 
  install_flutter: 
  ipaddr: 
  kill_tomcat: 
