name: dcli_scripts
version: 1.0.10
description: A collection of cli scripts that do odd jobs for me.
repository: https://github.com/bsutton/dcli_scripts
environment: 
  sdk: '>=2.14.0 <3.0.0'
dependencies: 
  dcli: ^1.14.1
  args: ^2.1.1
  path: ^1.6.4
  settings_yaml: ^3.0.6
  docker2: ^2.1.2
  pub_release: ^7.1.16
dev_dependencies: 
  lints: ^1.0.0
# dependency_overrides: 
#   dcli: 
#     path: ../dcli
#   dcli_core: 
#     path: ../dcli_core

executables: 
  add_gnome_launcher: 
  artifactory: 
  certbot_renew: 
  clean: 
  dcompress: 
  dcopydir: 
  denv: 
  dfind: 
  dmailhog: 
  dmysql: 
  dnsflush: 
  docker_dcli: 
  docker_push:
  downit: 
  dpath: 
  dport: 
  dreplace: 
  dsetver: 
  dsort: 
  dvirtualbox: 
  dwc: 
  dwhich: 
  dzfs_clean: 
  eclipse_launcher: 
  find_old_dart_packages: 
  gitadd_team_to_repository: 
  gitcreation_date: 
  gitgc: 
  gituncommited: 
  gitsyncfork: 
  gitupdate_remote: 
  hexdump: 
  hog: 
  install_flutter: 
  ipaddr: 
  kill_tomcat: 
  pub_get_all:
